drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
drop table if exists Cliente;
